package main

import (
	"bufio"
	"bytes"
	"context"
	"embed"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	schema "github.com/lestrrat-go/json-schema"
	"github.com/lestrrat-go/json-schema/validator"
	"github.com/lestrrat-go/json-schema/vocabulary"
)

// schemaFS holds the JSON Schema 2020-12 meta-schema and its vocabulary
// documents, copied verbatim from the published spec (with the canonical
// json-schema.org URIs). They are embedded so generation is hermetic: it needs
// no network access and is reproducible from version-controlled inputs.
//
//go:embed schemas
var schemaFS embed.FS

const (
	// schemaRoot is the directory inside schemaFS that holds the 2020-12 documents.
	schemaRoot = "schemas/2020-12"
	// baseURI is the canonical retrieval base the embedded documents are addressed
	// under. The root meta-schema's $id is baseURI+"schema"; its vocabulary
	// documents are baseURI+"meta/<name>".
	baseURI = "https://json-schema.org/draft/2020-12/"
	// rootRef is the canonical URI of the root meta-schema document.
	rootRef = baseURI + "schema"
)

func main() {
	if err := _main(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func _main() error {
	rootDir, err := findRootDir()
	if err != nil {
		return fmt.Errorf("failed to find root directory: %w", err)
	}

	// Register every embedded document so the meta-schema's cross-vocabulary
	// $refs (e.g. "meta/core") resolve from memory instead of over the network.
	resolver := schema.NewResolver()
	docs, err := loadEmbeddedSchemas()
	if err != nil {
		return err
	}
	for uri, doc := range docs {
		resolver.RegisterDocument(uri, doc)
	}

	root := docs[rootRef]
	if root == nil {
		return fmt.Errorf("root meta-schema %q not found in embedded schemas", rootRef)
	}

	ctx := context.Background()
	// Enable all vocabularies so the meta-schema compiles with every keyword it
	// uses across the core/applicator/validation/etc. vocabularies.
	ctx = vocabulary.WithSet(ctx, vocabulary.AllEnabled())
	ctx = schema.WithResolver(ctx, resolver)
	ctx = schema.WithBaseSchema(ctx, root)
	ctx = schema.WithBaseURI(ctx, baseURI)

	compiledValidator, err := validator.Compile(ctx, root)
	if err != nil {
		return fmt.Errorf("failed to compile meta-schema: %w", err)
	}

	var builderBuf bytes.Buffer
	if err := validator.NewCodeGenerator().Generate(&builderBuf, compiledValidator); err != nil {
		return fmt.Errorf("failed to generate validator code: %w", err)
	}

	packageContent := fmt.Sprintf(`// Code generated by internal/cmd/genmeta. DO NOT EDIT.

// Package meta provides a pre-compiled validator for JSON Schema 2020-12 meta-schema.
// This validator can be used to validate JSON Schema documents themselves.
package meta

import (
	"github.com/lestrrat-go/json-schema/keywords"
	"github.com/lestrrat-go/json-schema/validator"
)

func init() {
	// Ensure keywords package is imported (referenced by generated code)
	_ = keywords.Schema
}

// metaValidator holds the pre-compiled validator for the JSON Schema 2020-12 meta-schema
var metaValidator validator.Interface

func init() {
	// Generated validator using the code generator from the actual meta-schema
	metaValidator = %s
}
`, builderBuf.String())

	formattedCode, err := format.Source([]byte(packageContent))
	if err != nil {
		scanner := bufio.NewScanner(strings.NewReader(packageContent))
		line := 1
		for scanner.Scan() {
			fmt.Printf("%03d: %s\n", line, scanner.Text())
			line++
		}
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	outputPath := filepath.Join(rootDir, "meta", "meta_gen.go")
	if err := os.WriteFile(outputPath, formattedCode, 0o644); err != nil {
		return fmt.Errorf("failed to write generated code to %q: %w", outputPath, err)
	}

	fmt.Printf("Successfully generated meta-schema validator at: %s\n", outputPath)
	return nil
}

// loadEmbeddedSchemas parses every JSON document under schemaRoot and keys it by
// its canonical retrieval URI (baseURI joined with the path relative to
// schemaRoot, sans ".json" extension).
func loadEmbeddedSchemas() (map[string]*schema.Schema, error) {
	docs := make(map[string]*schema.Schema)
	err := fs.WalkDir(schemaFS, schemaRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".json") {
			return nil
		}
		data, err := schemaFS.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read embedded schema %q: %w", path, err)
		}
		var s schema.Schema
		if err := s.UnmarshalJSON(data); err != nil {
			return fmt.Errorf("failed to unmarshal embedded schema %q: %w", path, err)
		}
		rel := strings.TrimPrefix(path, schemaRoot+"/")
		uri := baseURI + strings.TrimSuffix(rel, ".json")
		docs[uri] = &s
		return nil
	})
	if err != nil {
		return nil, err
	}
	return docs, nil
}

// findRootDir finds the root directory containing the main go.mod file
func findRootDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		goModPath := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(goModPath); err == nil {
			content, err := os.ReadFile(goModPath)
			if err == nil && len(content) > 0 {
				// The main module's go.mod has no replace directive pointing the
				// module at itself (only the generator sub-modules do).
				if !bytes.Contains(content, []byte("replace github.com/lestrrat-go/json-schema")) {
					return dir, nil
				}
			}
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", fmt.Errorf("could not find root go.mod file")
}
