name: CI
on:
  pull_request:
    branches:
      - v*
      - develop/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24', '1.23' ]
    name: "Test [ Go ${{ matrix.go }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Cache testdata
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        env:
          TEST_SUITE_COMMIT: "48461fc3568972801b40eaccc428a31bce338f6e"
        with:
          path: tests
          key: ${{ runner.os }}-testdata-${{ env.TEST_SUITE_COMMIT }}
          restore-keys: |
            ${{ runner.os }}-testdata-
      - name: Setup testdata
        env:
          TEST_SUITE_COMMIT: "48461fc3568972801b40eaccc428a31bce338f6e"
        run: |
          if [ ! -d "tests" ] || [ ! -f "tests/README.md" ]; then
            git clone https://github.com/json-schema-org/JSON-Schema-Test-Suite.git tests
            cd tests && git checkout $TEST_SUITE_COMMIT
          else
            cd tests && git fetch origin && git checkout $TEST_SUITE_COMMIT
          fi
      - name: Cache Go modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/bazel
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Test 
        run: go test ./...
